version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore