services:
  localstack:
    container_name: localstack_documentBuilder
    image: localstack/localstack:latest
    ports:
      - "4561:4566"
    environment:
      - SERVICES=s3,dynamodb,kms
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh