version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
      - "4569:4569"
    environment:
      - SERVICES=dynamodb
      - HOSTNAME_EXTERNAL=localhost
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
    volumes:
      - ./localstack/provision.sh:/etc/localstack/init/ready.d/init-aws.sh
        
        
        
        
        
        