AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31
Description: >-
  Wallet Stub FE

Parameters:
  Environment:
    Description: "The environment type"
    Type: "String"
    Default: dev
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      # - "integration"
      # - "production"
  VpcStackName:
    Description: >
      The name of the stack that defines the VPC in which this container will
      run.
    Type: String
    Default: platform-vpc
  # BackendStackName:
  #   Description: >
  #     The name of the backend stack to depend on.  Is set to a default as not required for the higher envs.
  #   Type: String
  #   Default: backend-api
  ContainerPort:
    Description: >
      The port on which the container is running
    Type: Number
    Default: 8000

Mappings:
  # see https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html
  # PlatformConfiguration:
  #   dev:
  #     CSLSEGRESS: "This should not ever be set; the dev account is not configured to egress logs."
  #   build:
  #     CSLSEGRESS: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython
  #   staging:
  #     CSLSEGRESS: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython
  #   integration:
  #     CSLSEGRESS: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython
  #   production:
  #     CSLSEGRESS: arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython
  ECSConfiguration:
    dev:
      FrontImageRepository: TBC
    build:
      FrontImageRepository: TBC
    staging:
      FrontImageRepository: TBC
    integration:
      FrontImageRepository: TBC
    production:
      FrontImageRepository: TBC

Resources:

 # ECS RESOURCES

  WalletFEECSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: >-
        Wallet Stub Front ECS Security Group permitting outbound
        to anywhere.
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: '-1'
      VpcId:
        Fn::ImportValue:
          !Sub "${VpcStackName}-VpcId"

  WalletFECluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-WalletECSCluster"
        - Key: Product
          Value: "GOV.UK sign in"
        - Key: System
          Value: "Wallet Stub FE"
        - Key: Environment
          Value: !Sub "${Environment}"

  WalletFEEcsService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref WalletFECluster
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: TRUE
          Rollback: TRUE
      EnableECSManagedTags: false
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !GetAtt WalletFEECSSecurityGroup.GroupId
          Subnets:
            - Fn::ImportValue:
                !Sub "${VpcStackName}-ProtectedSubnetIdA"
            - Fn::ImportValue:
                !Sub "${VpcStackName}-ProtectedSubnetIdB"
            - Fn::ImportValue:
                !Sub "${VpcStackName}-ProtectedSubnetIdC"
      TaskDefinition: !Ref WalletFEECSServiceTaskDefinition
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-WalletECS"
        - Key: Product
          Value: "GOV.UK sign in"
        - Key: System
          Value: "Wallet FE Stub"
        - Key: Environment
          Value: !Sub "${Environment}"

  WalletFEECSServiceTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: CONTAINER-IMAGE-PLACEHOLDER
          Name: app
          Environment:
            # - Name: EXTERNAL_WEBSITE_HOST
            #   Value: !GetAtt WalletFEApiGwHttpEndpoint.ApiEndpoint
            # - Name: ENVIRONMENT
            #   Value: !Sub "${Environment}"
            - Name: PORT
              Value: !Ref ContainerPort
            # - Name: FRONT_END_URL
            #   Value: !Sub
            #     - "https://${Url}"
            #     - Url: !Ref WalletFEFrontCustomDomain
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group : !Ref WalletFEECSAccessLogsGroup
              awslogs-region : !Sub ${AWS::Region}
              awslogs-stream-prefix : !Sub wallet-stub-front-${Environment}
      Cpu: '1024' # Increased to use 1 CPU unit
      ExecutionRoleArn: !GetAtt WalletFEECSTaskExecutionRole.Arn
      Memory: '2048' # Upgraded memory value to match with increased CPU
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !GetAtt WalletFEECSTaskRole.Arn
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-WalletTaskDefinition"
        - Key: Product
          Value: "GOV.UK sign in"
        - Key: System
          Value: "Wallet Stub FE"
        - Key: Environment
          Value: !Sub "${Environment}"

  WalletFEECSTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: PullWalletFrontImage
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchCheckLayerAvailability"
                Resource:
                  - !FindInMap [ ECSConfiguration, !Ref Environment, FrontImageRepository ]
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !GetAtt "WalletFEECSAccessLogsGroup.Arn"
                  - !Sub "${WalletFEECSAccessLogsGroup.Arn}:*"
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  WalletFEECSTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: 2012-10-17
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  WalletFEECSAccessLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/ecs/${AWS::StackName}-WalletFront-ECS
      RetentionInDays: 14

# APIGW RESOURCES

  WalletFEApiGwHttpEndpoint:
      Type: 'AWS::ApiGatewayV2::Api'
      Properties:
        Name: !Sub wallet-stub-front-${Environment}-${AWS::StackName}
        Description: !Sub "Wallet Stub Frontend API. ${AWS::StackName}"
        ProtocolType: HTTP

  WalletFEApiGwHttpEndpointIntegration:
      Type: 'AWS::ApiGatewayV2::Integration'
      Properties:
        ApiId: !Ref WaletFEApiGwHttpEndpoint
        IntegrationType: HTTP_PROXY
        ConnectionId:
          Fn::ImportValue:
            !Sub "${VpcStackName}-VpcLinkId"
        ConnectionType: VPC_LINK
        IntegrationMethod: ANY
        PayloadFormatVersion: '1.0'
        RequestParameters:
          overwrite:header.x-govuk-signin-source-ip: $context.identity.sourceIp

  WalletFEAPIGWRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref WalletFEApiGwHttpEndpoint
      RouteKey: 'ANY /{proxy+}'
      Target: !Join
        - /
        - - integrations
          - !Ref WalletFEApiGwHttpEndpointIntegration

  WalletFEAPIStageDefault:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref WalletFEApiGwHttpEndpoint
      StageName: $default
      AutoDeploy: true
      DefaultRouteSettings:
        DataTraceEnabled: false
        DetailedMetricsEnabled: true
        ThrottlingBurstLimit: 400
        ThrottlingRateLimit: 1200
      AccessLogSettings:
        DestinationArn: !GetAtt WaletFEAPIGWAccessLogsGroup.Arn
        Format: >-
          {
          "requestId":"$context.requestId",
          "ip": "$context.identity.sourceIp",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "path": "$context.path",
          "routeKey":"$context.routeKey",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength"
          }

  WalletFEAPIGWAccessLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-WalletFE-API-GW-AccessLogs

  WalletFEFrontCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Sub "stub-credential-issuer.mobile.${Environment}.account.gov.uk"
      DomainNameConfigurations:
        - CertificateArn: !Sub "{{resolve:ssm:/${Environment}/Platform/ACM/PrimaryZoneWildcardCertificateARN}}"
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  WalletFEFrontApiRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref WalletFEFrontCustomDomain
      Type: A
      HostedZoneId: !Sub "{{resolve:ssm:/${Environment}/Platform/Route53/PrimaryZoneID}}"
      AliasTarget:
        DNSName: !GetAtt WaletFEFrontCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt WalletFEFrontCustomDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  WallFEFrontApiMapping:
    DependsOn: APIStageDefault
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref WaletFEFrontCustomDomain
      ApiId: !Ref WaletFEApiGwHttpEndpoint
      Stage: !Ref WaletFEAPIStageDefault
