name: Verify & Publish to Dev

on:
  workflow_dispatch:
    inputs:
      refType:
        type: choice
        description: "Find branch name or commit SHA?"
        options:
          - Branch name
          - Commit SHA
        default: Branch name
      gitRef:
        description: "Input branch name or commit SHA"
        required: true
        type: string
        default: main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
      ARTIFACT_BUCKET_NAME: ${{ secrets.DEV_ARTIFACT_SOURCE_BUCKET_NAME }}
      IMAGE_TAG: latest
      SAM_CLI_TELEMETRY: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.gitRef }}

      - name: Fetch Commit SHA
        if: ${{ github.event.inputs.choice }} == "Commit SHA"
        run: echo GIT_REF_SHA=${{ inputs.gitRef }} >> $GITHUB_ENV

      - name: Fetch Commit SHA by branch name
        if: ${{ github.event.inputs.choice }} == "Branch name"
        run: echo GIT_REF_SHA=$(git log -1 ${{ inputs.gitRef }} --pretty=format:%H) >> $GITHUB_ENV

      - name: Set tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Build & publish Docker image as latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_REF_SHA:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_REF_SHA:$IMAGE_TAG

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@819220f63fb333a9a394dd0a5cab2d8303fd17e2 # pin@v2
        with:
          version: 1.133.0
          use-installer: true

      - name: Deploy SAM application
        with:
          working-directory: ./deploy
        run: |
          echo "Running SAM build"
          sam build
          mv .aws-sam/build/template.yaml cf-template.yaml
          echo "Replacing 'CONTAINER-IMAGE-PLACEHOLDER' with new ECR image reference"
          sed -i "s|CONTAINER-IMAGE-PLACEHOLDER|$ECR_REGISTRY/$ECR_REPOSITORY:$GIT_REF_SHA|" cf-template.yaml
          zip template.zip cf-template.yaml
          echo "Uploading built SAM application to S3"
          aws s3 cp template.zip "s3://$ARTIFACT_BUCKET_NAME/template.zip" --metadata "repository=$GITHUB_REPOSITORY,commitsha=$GIT_REF_SHA"