name: Sonarcloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    name: Run Sonar scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v3
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm install
      # - name: Generate coverage report
      #   run: npm run test:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9 # pin@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}